// File generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart';

/// Firebase configuration - Replace these with your project credentials from Firebase Console
/// Get these from: Firebase Console → Project Settings → General → Service Accounts
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development placeholders - Update with real credentials from Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEVELOPMENT_WEB_API_KEY_PLACEHOLDER',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sign-translator-dev',
    authDomain: 'sign-translator-dev.firebaseapp.com',
    storageBucket: 'sign-translator-dev.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVELOPMENT_ANDROID_API_KEY_PLACEHOLDER',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sign-translator-dev',
    storageBucket: 'sign-translator-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVELOPMENT_IOS_API_KEY_PLACEHOLDER',
    appId: '1:000000000000:ios:0000000000000001',
    messagingSenderId: '000000000000',
    projectId: 'sign-translator-dev',
    storageBucket: 'sign-translator-dev.appspot.com',
    iosBundleId: 'com.example.signTranslate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEVELOPMENT_MACOS_API_KEY_PLACEHOLDER',
    appId: '1:000000000000:macos:0000000000000002',
    messagingSenderId: '000000000000',
    projectId: 'sign-translator-dev',
    storageBucket: 'sign-translator-dev.appspot.com',
    iosBundleId: 'com.example.signTranslate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEVELOPMENT_WINDOWS_API_KEY_PLACEHOLDER',
    appId: '1:000000000000:windows:0000000000000003',
    messagingSenderId: '000000000000',
    projectId: 'sign-translator-dev',
    storageBucket: 'sign-translator-dev.appspot.com',
  );
}
